name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Containers
        run: docker-compose -f docker/docker-compose.yml build

      - name: Run Tests
        run: docker-compose run --rm app npm test

      - name: Deploy to Staging
        if: success()
        run: echo "Deploying to staging environment..."

      - name: Deploy to Production
        if: github.event_name == 'push' && success()
        run: echo "Deploying to production..."
